<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $title
 * @property string $body
 * @property PostCategory $PostCategory
 * 
 * @method integer      getCategoryId()   Returns the current record's "category_id" value
 * @method string       getTitle()        Returns the current record's "title" value
 * @method string       getBody()         Returns the current record's "body" value
 * @method PostCategory getPostCategory() Returns the current record's "PostCategory" value
 * @method Post         setCategoryId()   Sets the current record's "category_id" value
 * @method Post         setTitle()        Sets the current record's "title" value
 * @method Post         setBody()         Sets the current record's "body" value
 * @method Post         setPostCategory() Sets the current record's "PostCategory" value
 * 
 * @package    site
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PostCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}