PostCategory:
  columns:
    name: { type: string(255), notnull: true, unique: true }
 
Post:
  columns:
    category_id:  { type: integer, notnull: true }
    title:         { type: string(255) }
    body: { type: string(4000) }
  relations:
    PostCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: Posts } 
 
