PostCategory:
  columns:
    name: { type: string(255), notnull: true, unique: true }
 
Post:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    title: { type: string(255) }
    body: { type: string(4000) }
  relations:
    PostCategory: { local: category_id, foreign: id, foreignAlias: Posts } 

User:
  columns:
    name: { type: string(255) , unique: true, notnull: true }
    password: { type: string(255) , notnull: true }
 
