<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/14 02:28:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=site-juanma',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
