<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/07/17 23:26:47
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinepager' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sftesterdoctrine' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfformdoctrine' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecli' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineroute' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfwebdebugpaneldoctrine' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfvalidatordoctrineunique' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfwidgetformdoctrinechoice' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineformgenerator' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinegenerator' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineconnectionlistener' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'swift_doctrinespool' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecordi18nfilter' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinebuildtask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebuildformstask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinedataloadtask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedqltask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinegenerateadmintask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinedatadumptask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrineinsertsqltask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildmodeltask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildfilterstask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinebasetask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinecreatemodeltables' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuildsqltask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinemigratetask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinedropdbtask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/var/www/site-juanma-symfony/site/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',

  // project
  'baseform' => '/var/www/site-juanma-symfony/site/lib/form/BaseForm.class.php',
  'baseuserform' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/base/BaseUserForm.class.php',
  'basepostcategoryform' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/base/BasePostCategoryForm.class.php',
  'basepostform' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/base/BasePostForm.class.php',
  'postcategoryform' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/PostCategoryForm.class.php',
  'userform' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/UserForm.class.php',
  'baseformdoctrine' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/BaseFormDoctrine.class.php',
  'postform' => '/var/www/site-juanma-symfony/site/lib/form/doctrine/PostForm.class.php',
  'userformfilter' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/UserFormFilter.class.php',
  'baseuserformfilter' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/base/BaseUserFormFilter.class.php',
  'basepostformfilter' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/base/BasePostFormFilter.class.php',
  'basepostcategoryformfilter' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/base/BasePostCategoryFormFilter.class.php',
  'baseformfilterdoctrine' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'postformfilter' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/PostFormFilter.class.php',
  'postcategoryformfilter' => '/var/www/site-juanma-symfony/site/lib/filter/doctrine/PostCategoryFormFilter.class.php',

  // project_model
  'usertable' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/UserTable.class.php',
  'user' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/User.class.php',
  'basepostcategory' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/base/BasePostCategory.class.php',
  'basepost' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/base/BasePost.class.php',
  'baseuser' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/base/BaseUser.class.php',
  'postcategory' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/PostCategory.class.php',
  'post' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/Post.class.php',
  'postcategorytable' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/PostCategoryTable.class.php',
  'posttable' => '/var/www/site-juanma-symfony/site/lib/model/doctrine/PostTable.class.php',

  // application
  'myuser' => '/var/www/site-juanma-symfony/site/apps/frontend/lib/myUser.class.php',

  // modules
);
