<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/07/17 23:26:55
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
);
